### ISSUE TITLE
mameui64 ui issues with mame.189

### ISSUE THREAD

**Issue by mk-destany** [Robbbert/mameui#32] opened 2017-09-02 05:42 UTC
1st time posting, but with the 189 release, the ui has messed up badly...

1st one is fullscreen , 2nd is windowed.... this wasn't issue with 188

![untitled](https://user-images.githubusercontent.com/31559850/29993257-b19abd1c-8f66-11e7-8f28-ce336d8891e7.jpg)
![untitled2](https://user-images.githubusercontent.com/31559850/29993259-b79c65f8-8f66-11e7-8ebf-fd870790ffca.jpg)

**Comment by mk-destany** [comment] 2017-09-02 05:42
this is on a clean install of mameui64

**Comment by Robbbert** [comment] 2017-09-03 02:38
Just found out about this (no notifications received).

So, no QA department here, it's a one-man operation.

Now, to your issue. It's known, and there's a workaround in the changelog which you haven't read.
http://www.1emulation.com/forums/topic/35880-messui-and-mameui-0189-released/

Specifically:
 When you first try setting up MESSUI/MAMEUI, there's a problem with the splitters covering up the list of games. There's a workaround:
_"Start MESSUI/MAMEUI. Drag out the bottom-right corner to expand it to the desired size (even though it looks like crap). Close it. Open it. Now you can adjust the splitters and it will look ok. Close it again to save the settings. Next time you open it, everything will be fine."_

The problem is scheduled to be worked on during this month.

Also, you should get a new MAMEUI64.exe from the site mentioned in that link, some other bug fixes have been applied.

**Comment by Robbbert** [comment] 2017-09-03 12:50
Nothing further heard, closing.

**Closed by Robbbert** 2017-09-03 12:50 UTC
